---
#
# This sets up the configuration files used by the "jrnl" command line
# utility, See also: https://github.com/maebert/jrnl
#
- name: create base directory structure
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: 0755
  with_items:
    - gdrive
    - gdrive/JRNL

- name: create base file structure
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: touch
    owner: "{{ ansible_env.USER }}"
    mode: 0755
  with_items:
    - gdrive/JRNL/default.jrnl

- name: copy drive configuration files
  copy:
    src: "home/user/"
    dest: "{{ ansible_env.HOME }}/"
    owner: "{{ ansible_env.USER }}"
    mode: 0644
