---
- name: create base directory structure
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: 0755
  with_items:
    - .local
    - .local/bin

- name: copy executable files
  copy:
    src: "home/user/"
    dest: "{{ ansible_env.HOME }}/"
    owner: "{{ ansible_env.USER }}"
    mode: 0755
