language: python
python: "2.7"
branches:
  only:
    - staging
    - trying
    - master

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible

script:
  - ./scripts/apply-playbook.sh
