---
- name: create base directory structure
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: 0755
  with_items:
    - .local
    - .local/bin

- name: install diff-so-fancy
  get_url:
    url: "https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy"
    dest: "{{ ansible_env.HOME }}/.local/bin/diff-so-fancy"
    validate_certs: no
    mode: 0755
