---
- name: copy bash configuration files
  copy:
    src: "home/user/"
    dest: "{{ ansible_env.HOME }}/"
    owner: "{{ ansible_env.USER }}"
    mode: 0644

- name: create include directory
  file:
    path: "{{ ansible_env.HOME }}/.bashrc.d"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: 0755

- name: uninstall git-prompt file
  file:
    path: "{{ ansible_env.HOME }}/.bashrc.d/50-git-prompt.bash"
    state: absent

- name: install liquidprompt file
  get_url:
    url: "https://raw.githubusercontent.com/nojhan/liquidprompt/master/liquidprompt"
    dest: "{{ ansible_env.HOME }}/.bashrc.d/liquidprompt"
    validate_certs: no

- name: install pyenv
  git:
    repo: "git://github.com/pyenv/pyenv.git"
    dest: "{{ ansible_env.HOME }}/.pyenv"
    update: yes
    depth: 1
    accept_hostkey: yes

- name: install pyenv plugins
  git:
    repo: "git://github.com/pyenv/{{ item }}.git"
    dest: "{{ ansible_env.HOME }}/.pyenv/plugins/{{ item }}"
    update: yes
    depth: 1
    accept_hostkey: yes
  with_items:
    - pyenv-virtualenv
