---
- name: copy tmux configuration files
  copy:
    src: "home/user/"
    dest: "{{ ansible_env.HOME }}/"
    owner: "{{ ansible_env.USER }}"
    mode: 0644

- name: create .tmux directory
  file:
    path: "{{ ansible_env.HOME }}/.tmux"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: 0755

- name: install tmux plugins
  git:
    repo: "git://github.com/tmux-plugins/{{ item }}.git"
    dest: "{{ ansible_env.HOME }}/.tmux/{{ item }}"
    update: yes
    depth: 1
    force: yes
    accept_hostkey: yes
  with_items:
    - tmux-copycat
    - tmux-open
    - tmux-pain-control
    - tmux-sensible
    - tmux-yank
